version: '2'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 9002:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/var/www/html:ro
